"""Markdown report generation for the analysis session."""

import time
from collections import deque

from .config import MAX_HUMAN_KPS, LOW_JITTER_THRESHOLD, OBS_MAX_LOG, TRUSTED_TEST_DURATION


def generate_report(
    *,
    os_type: str,
    focused_usb: str | None,
    devices: list[str],
    trusted: set[str],
    alert_log: list[str],
    obs_log: deque[str],
) -> str:
    """
    Generate a sober Markdown report for the current session.

    Returns:
        Full Markdown string ready to be written to disk.
    """
    ts       = time.strftime("%Y-%m-%d %H:%M:%S")
    mode_str = f"FOCUS ({focused_usb})" if focused_usb else "WATCH"

    sections: list[str] = []

    # Header
    sections.append("# BadUSB Heuristic Analysis Report")
    sections.append("")

    # Session metadata table
    sections.append("## Session Metadata")
    sections.append("")
    sections.append("| Field | Value |")
    sections.append("|---|---|")
    sections.append(f"| Generated | {ts} |")
    sections.append(f"| Platform | {os_type} |")
    sections.append(f"| Active mode | {mode_str} |")
    sections.append(f"| Speed threshold | {MAX_HUMAN_KPS} CPS |")
    sections.append(f"| Jitter threshold | {LOW_JITTER_THRESHOLD} s |")
    sections.append(f"| Trust period | {TRUSTED_TEST_DURATION} s |")
    sections.append("")

    # 1. Detected USBs
    sections.append("## 1. Detected USB Devices")
    sections.append("")
    if devices:
        for i, d in enumerate(devices, 1):
            sections.append(f"{i}. {d}")
    else:
        sections.append("No devices detected at the time of saving.")
    sections.append("")

    # 2. Trusted USBs
    sections.append("## 2. Trusted USB Devices")
    sections.append("")
    if trusted:
        for i, d in enumerate(sorted(trusted), 1):
            sections.append(f"{i}. {d}  (no alerts > {TRUSTED_TEST_DURATION}s)")
    else:
        sections.append("No device has completed the verification period.")
    sections.append("")

    # 3. Critical alerts
    sections.append("## 3. Critical Alerts")
    sections.append("")
    if alert_log:
        for i, line in enumerate(alert_log, 1):
            sections.append(f"{i}. {line}")
    else:
        sections.append("No alerts recorded this session.")
    sections.append("")

    # 4. Observation log
    sections.append(f"## 4. Keystroke Dynamics (last {OBS_MAX_LOG} entries)")
    sections.append("")
    if obs_log:
        sections.append("```")
        sections.extend(obs_log)
        sections.append("```")
    else:
        sections.append("No observation entries recorded.")
    sections.append("")

    # Footer
    sections.append("---")
    sections.append("Report generated by the BadUSB Heuristic Analysis System — UAH TFG")

    return "\n".join(sections)
